openapi: 3.0.0
info:
  version: '1.0'
  title: premises
  description: 'Get premises details based on accountNumber'
paths: 
  /customers/premises:
    get:
      summary: customer premises
      description: Retrieve customer's premises details
      tags: 
        - Premises
      parameters:
        - in: query
          name: accountNumber
          required: true
          schema:
            type: string
            format: number
            example: 909768523005
      responses:
        200:
          description: premises details retrieved successfully
          content:
            application/vnd.api+json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/ng-premises'
        400:
          description: Invalid request
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        401:
          description: Unauthorized
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        404:
          description: User not found
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        500:
          description: Internal Server Error
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    ng-premises:
      type: object
      required:
        - customerId
      properties:
        accountNumber:
          type: string
          example: "909768523005"  
        premises:
          type: array
          items:
            type: object
            properties:
              premiseId:
                type: string
                example: 00224801EEEB5C
              premise:
                type: string
                example: 49 Featherstone Street, EC1Y 8SY
    BadRequestError:
      type: object
      properties:
        errors:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
                  example: Invalid request
                code:
                  type: integer
                  example: 400
    UnauthorizedError:
      type: object
      properties:
        errors:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
                  example: 'Unauthorized'
                code:
                  type: integer
                  example: 401
    NotFoundError:
      type: object
      properties:
        errors:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
                  example: 'Not found'
                code:
                  type: integer
                  example: 404
    InternalServerError:
      type: object
      properties:
        errors:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
                  example: 'Internal server error'
                code:
                  type: integer
                  example: 500
servers:
  - description: Premises API 
    url: http://localhost:3000